[package]
name = "httpbin"
version = "0.1.0"
edition = "2024"
description = "Simple HTTP echo server to provide endpoint that echoes back request data"
rust-version = "1.91"
readme = "README.md"
repository = "https://github.com/DoumanAsh/httpbin"
license = "BSL-1.0"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]

[dependencies]
timeout-context = "0.2"
pin-project-lite = "0.2"
http = "1"

[dependencies.tokio]
version = "1"
default-features = false
features = ["rt", "net", "time"]

[dependencies.hyper]
version = "1"
default-features = false
features = ["server", "http1"]

[profile.release]
lto = 'thin'
opt-level = 3
codegen-units = 1
strip = true
debug = false
